"""Disk-backed store for images a TOOL produced during an agent turn.

Before this, an image coming out of a tool had two unrelated fates and no
shared path:

  * `result["vision_images"]` went to the MODEL as vision input on the tool
    result, and the user saw nothing at all in the chat.
  * `result["images"]` (browser screenshots) went to the FRONTEND as a
    base64 `screenshot` field — first image only — and vanished on reload,
    because it was never written into the persisted tool event.

This module is the one place both now go through. Bytes land in
TOOL_IMAGES_DIR under an opaque filename and the chat carries a short URL,
so a 50 KB PNG per rendered view never ends up base64-inlined in
`chat_messages.metadata` (which is re-sent in full on every session load).
The model's copy stays in-memory base64 — see agent_loop's
`_tool_result_content` — since that has to be inline in the API payload.

Files here are served over HTTP by name (routes/chat_routes.py's
`/api/chat/tool-image/{name}`), which is exactly why they live in their own
directory rather than alongside the user's uploaded attachment blobs, and
why `is_safe_name()` is the gate rather than a path join with validation
left to the caller.
"""

import base64
import binascii
import logging
import os
import re
import time
import uuid

from src.constants import TOOL_IMAGES_DIR

logger = logging.getLogger(__name__)

# Opaque, generated by us — never a caller-supplied or model-supplied name.
_SAFE_NAME_RE = re.compile(r"^[A-Za-z0-9_-]{1,120}\.(?:png|jpg|jpeg|gif|webp)$")

_EXT_BY_MIME = {
    "image/png": "png",
    "image/jpeg": "jpg",
    "image/jpg": "jpg",
    "image/gif": "gif",
    "image/webp": "webp",
}

# A single tool call can legitimately return several images (a renderer may
# emit one per requested view). This is a backstop against a pathological
# result, not a normal limit.
MAX_IMAGES_PER_RESULT = 12


def is_safe_name(name: str) -> bool:
    """True if `name` is one of our own generated filenames.

    Rejects anything with a path separator, `..`, or an unexpected
    extension, so the serving route can never be walked out of the
    directory.
    """
    return bool(_SAFE_NAME_RE.match(name or ""))


def _decode(data) -> "bytes | None":
    if isinstance(data, (bytes, bytearray)):
        return bytes(data)
    if not isinstance(data, str) or not data:
        return None
    # Tolerate a full data URI as well as bare base64 — browser MCP tools and
    # our own renderers disagree on which they hand back.
    if data.startswith("data:") and ";base64," in data:
        data = data.split(";base64,", 1)[1]
    try:
        return base64.b64decode(data, validate=False)
    except (binascii.Error, ValueError):
        return None


def save_tool_images(images: list, *, tool: str = "") -> list:
    """Write tool-produced images to disk; return [{url, title, name}].

    `images` is the list shape both `vision_images` and `images` already
    use: `{"mimeType": ..., "data": <base64>, "title": ...}`. Anything that
    fails to decode is skipped rather than raising — an unrenderable image
    must never take down the tool call that produced it.
    """
    if not images:
        return []
    saved = []
    try:
        os.makedirs(TOOL_IMAGES_DIR, exist_ok=True)
    except OSError as e:
        logger.warning("Cannot create tool image dir: %s", e)
        return []
    for idx, img in enumerate(images[:MAX_IMAGES_PER_RESULT]):
        if not isinstance(img, dict):
            continue
        raw = _decode(img.get("data"))
        if not raw:
            continue
        mime = str(img.get("mimeType") or "image/png").lower()
        ext = _EXT_BY_MIME.get(mime, "png")
        name = f"{int(time.time())}_{uuid.uuid4().hex[:12]}_{idx}.{ext}"
        try:
            with open(os.path.join(TOOL_IMAGES_DIR, name), "wb") as f:
                f.write(raw)
        except OSError as e:
            logger.warning("Failed to persist tool image from %s: %s", tool or "?", e)
            continue
        saved.append({
            "url": f"/api/chat/tool-image/{name}",
            "name": name,
            "title": str(img.get("title") or "")[:120],
        })
    return saved


def collect_result_images(result: dict) -> list:
    """Every image a tool result carries, from either field.

    `vision_images` and `images` are kept as separate result fields because
    they mean different things to the MODEL (see agent_loop's
    `_VISION_TOOL_RESULTS`), but for display purposes an image is an image.
    """
    out = []
    for key in ("vision_images", "images"):
        val = result.get(key)
        if isinstance(val, list):
            out.extend(v for v in val if isinstance(v, dict))
    return out
